"""empty message

Revision ID: 53c413d1be59
Revises: 
Create Date: 2023-09-28 17:29:11.240341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c413d1be59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('titulo', sa.String(length=255), nullable=True),
                    sa.Column('plataforma', sa.String(
                        length=255), nullable=True),
                    sa.Column('estilo', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogo')
    # ### end Alembic commands ###
