"""empty message

Revision ID: d4dab346bb90
Revises: 53c413d1be59
Create Date: 2023-10-18 20:44:59.224357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dab346bb90'
down_revision = '53c413d1be59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('console', sa.String(length=255), nullable=True),
                    sa.Column('genre', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('jogo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogo',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('titulo', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('plataforma', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('estilo', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('game')
    # ### end Alembic commands ###
